Feature 2 add middle section mobile
MostafaShahat2021/portfolio pull request #5
Opened 2022-08-24 12:26 UTC by MostafaShahat2021

### In this project we :
- Add second section ( Work - About ). 
- Add Linters for HTML/CSS.
- Use Mobile-first approach.
- Use best practices for HTML & CSS.
- Update README file.
- Add Mark up to the .html file.
- Add style to the main header.
- Use images and backgrounds to enhance the look of the website.

2022-08-24 13:10 UTC, franclobo requested changes
Hi @MostafaShahat2021, 

You are doing it well, congratulations!!! 😄 
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights

- No linter errors ✔️
- Correct Github flow 💯 
- Descriptive PR ✔️ ✔️ 
- Professional README file 💯 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Please 🙏🏽 review the Figma [template # 4](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=23%3A10) and make your portfolio similar to this template. 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-24 13:10 UTC, franclobo commented on index.html
> +        </section>
In the case of Figma template # 4, these skills replace the About section. 👆🏽

2022-08-24 13:10 UTC, franclobo commented on index.html
> +    <!-- ----SECOND SECTION START -------->
- [ ] Please 🙏🏽 the Work section should be inside the `<section>` tag for the best practices for HTML & CSS.

2022-08-24 13:10 UTC, franclobo commented on styles.css
> +  font-weight: 500;
- [ ] Kindly correct the font -weight to be similar to the Figma template. 👇🏽

![image](https://user-images.githubusercontent.com/58642949/186423847-5d1f9028-a21a-462e-9836-7cfc470b3bd0.png)

2022-08-24 13:10 UTC, franclobo commented on index.html
> +            </a>
- [ ] Kindly, complete the icons there are 5 in the Figma template, and make sure that they show in the browser. 👇🏽 
- [ ] Please 🙏🏽 use the `<ul>` tag like a container of the icons, for the best practices for HTML & CSS.

- Your design

![image](https://user-images.githubusercontent.com/58642949/186424598-5280ab6c-610d-4f55-b0ce-c67e6152d3ab.png)

- Figma template
![image](https://user-images.githubusercontent.com/58642949/186424702-7bc8c81e-6ef6-4d73-af4a-06a8838424c9.png)

2022-08-24 13:10 UTC, franclobo commented on index.html
> +        </article>
- [ ] This About section is one with the Home page in Figma template # 4. Kindly delete this section to look similar to the Figma template.

2022-08-24 15:24 UTC, MostafaShahat2021 commented
Hi @franclob
Thank you for your efforts in reviewing my code,
1- Add work section inside section tag.
2- Make sure that icons show in the browser.
3- make sure that my recent work title has the same font-weight as the Figma template.
thank you, have a good day,
Best Regards.
![fix issues](https://user-images.githubusercontent.com/79546797/186458290-a3e5f8ea-cb69-4558-8037-3ffd6833d9f3.jpg)

2022-08-24 15:45 UTC, codecaiine approved these changes
Hi @MostafaShahat2021 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Great project implementation :heavy_check_mark: 
- Good UI design :heavy_check_mark: 
- Descriptive PR :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-24 15:45 UTC, codecaiine commented on index.html
> +            <button type="button" class="btn">See Project</button>
- [ ] [OPTIONAL] Good job so far :smile: but please follow the button styling: Active, Hover and Pressed  as defined on Figma design :smile: 
![Screenshot from 2022-08-24 15-40-58](https://user-images.githubusercontent.com/6615394/186462786-29b7aec2-0274-446c-af60-f2e117e1ec0d.png)

2022-08-24 16:26 UTC, merged

2022-10-11 07:44 UTC, MostafaShahat2021 commented
*Hi ***@***.****
*Thank you for your efforts in reviewing my code,*
*1- Add work section inside section tag.*
*2- Make sure that icons show in the browser.*
[image: image.png]

*3- make sure that my recent work title has the same font-weight as the
Figma template.*
[image: image.png]


*thank you, have a good day,*
*Best Regards.*


On Wed, Aug 24, 2022 at 3:10 PM Francisco Borja Lobato <
***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @MostafaShahat2021 <https://github.com/MostafaShahat2021>,
>
> You are doing it well, congratulations!!! 😄
> Good job so far!
> There are some issues that you still need to work on to go to the next
> project but you are almost there!
> Highlights
>
>    - No linter errors ✔️
>    - Correct Github flow 💯
>    - Descriptive PR ✔️ ✔️
>    - Professional README file 💯
>
> Required Changes ♻️
>
> *Check the comments under the review.*
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> You can also consider:
>
>    - Please 🙏🏽 review the Figma template # 4
>    <https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=23%3A10>
>    and make your portfolio similar to this template.
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In index.html
> <https://github.com/MostafaShahat2021/portfolio/pull/5#discussion_r953757132>
> :
>
> > +        <section class="skils-container">
>
> +            <div class="cont">
>
> +                <span>language</span>
>
> +                <ul>
>
> +                    <li>Javascript</li>
>
> +                    <li>Ruby</li>
>
> +                    <li>Html</li>
>
> +                    <li>Css</li>
>
> +                </ul>
>
> +            </div>
>
> +            <div class="cont">
>
> +                <span>Frameworks</span>
>
> +                <ul class="list">
>
> +                    <li>Bootstrap</li>
>
> +                    <li>Ruby On Rials</li>
>
> +                    <li>RSPec</li>
>
> +                    <li>CapyBara</li>
>
> +                    <li>Selenium</li>
>
> +                </ul>
>
> +            </div>
>
> +            <div class="cont">
>
> +                <span>Skils</span>
>
> +                <ul class="list">
>
> +                    <li>Codekit</li>
>
> +                    <li>Github</li>
>
> +                    <li>Codepen</li>
>
> +                    <li>Gitlab</li>
>
> +                    <li>Terminal</li>
>
> +                </ul>
>
> +            </div>
>
> +        </section>
>
>
> In the case of Figma template # 4, these skills replace the About section.
> 👆🏽
> ------------------------------
>
> In index.html
> <https://github.com/MostafaShahat2021/portfolio/pull/5#discussion_r953764175>
> :
>
> >          </div>
>
> -        <div class="cont">
>
> -            <span>Skils</span>
>
> -            <ul class="list">
>
> -                <li>Codekit</li>
>
> -                <li>Github</li>
>
> -                <li>Codepen</li>
>
> -                <li>Gitlab</li>
>
> -                <li>Terminal</li>
>
> -            </ul>
>
> -        </div>
>
> -    </section>
>
> +        <img class="work" src="img/Element-Right.png" alt="">
>
> +    </div>
>
> +
>
> +    <!-- ----SECOND SECTION START -------->
>
>
>
>    - Please 🙏🏽 the Work section should be inside the <section> tag for
>    the best practices for HTML & CSS.
>
> ------------------------------
>
> In styles.css
> <https://github.com/MostafaShahat2021/portfolio/pull/5#discussion_r953766532>
> :
>
> > +
>
> +.second-container {
>
> +  display: grid;
>
> +  grid-template-columns: 1fr;
>
> +  grid-template-rows: 1fr 1fr 1fr 1fr;
>
> +  align-content: center;
>
> +  background: url("/img/portfolio.png");
>
> +  background-position: center;
>
> +  background-repeat: no-repeat;
>
> +  background-size: 100%;
>
> +  height: fit-content;
>
> +}
>
> +
>
> +.work-titl {
>
> +  font-size: 40px;
>
> +  font-weight: 500;
>
>
>
>    - Kindly correct the font -weight to be similar to the Figma template.
>    👇🏽
>
> [image: image]
> <https://user-images.githubusercontent.com/58642949/186423847-5d1f9028-a21a-462e-9836-7cfc470b3bd0.png>
> ------------------------------
>
> In index.html
> <https://github.com/MostafaShahat2021/portfolio/pull/5#discussion_r953772270>
> :
>
> > +        <div class="social">
>
> +            <a href="https://github.com/MostafaShahat2021" rel="noopener noreferrer nofollow" target="_blank">
>
> +                <img src="/img/git.png" alt="GitHub-Profile">
>
> +            </a>
>
> +            <a href="https://www.linkedin.com/in/mostafa-shahat-a75810208/" rel="noopener noreferrer nofollow"
>
> +                target="_blank">
>
> +                <img src="/img/linkedin.png" alt="LinkedIn-profile">
>
> +            </a>
>
> +            <a href="#" rel="noopener noreferrer nofollow" target="_blank">
>
> +                <img src="/img/Angelist.png" alt="">
>
> +            </a>
>
> +            <a href="https://twitter.com/Mostafa99738811" rel="noopener noreferrer nofollow" target="_blank">
>
> +                <img src="img/Vectotr.png" alt="twitter">
>
> +            </a>
>
> +            <a href="#" rel="noopener noreferrer nofollow" target="_blank">
>
> +                <img src="img/Vector1.png" alt="">
>
> +            </a>
>
>
>
>    -
>
>    Kindly, complete the icons there are 5 in the Figma template, and make
>    sure that they show in the browser. 👇🏽
>    -
>
>    Please 🙏🏽 use the <ul> tag like a container of the icons, for the
>    best practices for HTML & CSS.
>    -
>
>    Your design
>
> [image: image]
> <https://user-images.githubusercontent.com/58642949/186424598-5280ab6c-610d-4f55-b0ce-c67e6152d3ab.png>
>
>    - Figma template
>    [image: image]
>    <https://user-images.githubusercontent.com/58642949/186424702-7bc8c81e-6ef6-4d73-af4a-06a8838424c9.png>
>
> ------------------------------
>
> In index.html
> <https://github.com/MostafaShahat2021/portfolio/pull/5#discussion_r953779244>
> :
>
> > +        <article class="card-container">
>
> +            <h2 class="work-titl">About</h2>
>
> +            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore
>
> +                et
>
> +                dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
>
> +                aliquip
>
> +                ea eiusmod</p>
>
> +            <button type="button" class="btn">Get my CV</button>
>
> +
>
> +            <section class="skils-container2">
>
> +                <div class="cont">
>
> +                    <div class="skill-list">
>
> +                        <span>language</span>
>
> +                        <span class="material-symbols-outlined">
>
> +                            expand_more
>
> +                        </span>
>
> +                    </div>
>
> +                    <ul>
>
> +                        <li>Javascript</li>
>
> +                        <li>Ruby</li>
>
> +                        <li>Html</li>
>
> +                        <li>Css</ [...]